### ISSUE TITLE
convenience function to get the highest level of the hierarchy

### ISSUE THREAD

**Issue by lvsltz** [oruebel/ndx-icephys-meta#19]
Some experiments might not have a `ic_conditions` or a `ic_runs` table. So if one needs to retrieve the whole hierarchy at once (for example with `ic_conditions.to_denormalized_dataframe()`) they should be able to do it without querying to see if these tables exist in the first place.

**Comment by oruebel** [comment]
Sounds good. I believe that function would need to live on NWBFile.

**Comment by oruebel** [comment]
@lvsltz I just added the function ``get_ic_meta_parent_table`` in #44 that should address this issue.
