### ISSUE TITLE
CurrentClampStimulusSeries and VoltageClampSeries combined in add_intracellular_recording

### ISSUE THREAD

**Issue by lvsltz** [oruebel/ndx-icephys-meta#22]
In the notebook provided as example at https://github.com/oruebel/ndx-icephys-meta/blob/master/src/pynwb/examples/icephys_meta_to_pandas.ipynb, `CurrentClampStimulusSeries` and `VoltageClampSeries` are added as stimulus and response in the `intracellular_recordings` table (Section _3. Construct our Intracellular Electrophysiolgy Metadata tables_, paragraph _Add intracelluar recordings_).

Not only this is not ideal for a tutorial, because it's creating confusion, but `add_intracellular_recording` should actually raise an exception if incompatible classes are stored together. (I think they are incompatible...)

**Comment by oruebel** [comment]
See also https://github.com/oruebel/ndx-icephys-meta/issues/38 for additional comments.

**Comment by oruebel** [comment]
In the unit tests this got fixed in #42. Still need to fix this in the examples.
