### ISSUE TITLE
Add Stimulus and Reponse tables

### ISSUE THREAD

**Issue by oruebel** [oruebel/ndx-icephys-meta#31]
As part of the hackathon it was identified that we should add tables for ``intracellular_stimulus`` and ``intracellular_response``, which in turn are referenced from the ``intracellular_recordings`` table. This is to avoid mixing metadata specific to stimulus and response in the same table.

**Comment by oruebel** [comment]
Since the different tables (stimuluys, response, recording) would need to align (i.e., have the same number of rows), rather than referencing it seems like it would be simpler to implement this as a collection of tables. This would in effect be a categorical table, i.e., we would have a ``Group`` (call ``intracellular_recordings``) that would contain a set of ``DynamicTable``, one for each category (here ``stimulus``, ``response``, and ``electrode``). This approach would have the advantage that we: (a) simplify implementation and avoid introducing another layer of references, (b) can add new categories by allowing to add new DynamicTables, (c) improve performance by avoiding the need for resolving many references, (d) create a new reusable data-type for categorical tables.

**Comment by oruebel** [comment]
After talking with @ajtritt, rather than doing a collection of ``DynamicTables`` we think that it will be better to extend ``DynamicTable`` itself and add support for grouping of columns by "category", i.e., in addition to name, each column would also be assigned a category label. In this case we would have three categories, ``electrode``, ``stimulus`` and ``response``. All data would in this way still be stored in the same table, but it would be clear to which category each column belongs to.

**Comment by lvsltz** [comment]
I think it's a very good idea.
