### ISSUE TITLE
Define more descriptive names for the tables

### ISSUE THREAD

**Issue by oruebel** [oruebel/ndx-icephys-meta#32]
We should use descriptive names for the tables that: 1) better communicate the intended use of the tables and 2) avoid overlap with terms used in the community that are ambiguous. Suggested names are:

1) ``intracellular_stimuli``  (new, see #31)
1) ``intracellular_responses`` (new, see #31)
1) ``intracellular_recordings`` (remain as is)
1) ``sweeps`` ---rename to---> `` simultaneous_recordings``
1) ``sweep_sequence``  ---rename to---> ``sequential_recordings``
1) ``runs`` ---rename to ---> ``repetitions``
1) ``conditions`` ---rename to---> ``experimental_conditions``

Also rename the columns

**Comment by lvsltz** [comment]
Also consider 
6. `runs` ---rename to ---> `repetitions`

**Comment by oruebel** [comment]
> Also consider `runs` ---rename to ---> `repetitions`

@lvsltz thanks for the suggestion. I agree, that  term sounds much better. I'll update accordingly as I implement this issue.

**Comment by oruebel** [comment]
See also #27 which should be handled at the same time as this issue
