### ISSUE TITLE
API: add_intracellular_recording

### ISSUE THREAD

**Issue by t-b** [oruebel/ndx-icephys-meta#34]
```
nwbfile.add_intracellular_recording(electrode=electrode,
                                    stimulus=stim,
                                    response=resp,
                                    id=sweep_number
                                    )
```

- All arguments should be optional, of course skipping all does not make sense.

- If both stimulus and response are PatchClampSeries they should also both
reference the same electrode and sweep (if not raise an exception).

- It should also raise an error if you mix stimulus and response in a intracellular recording in an erroneous way.

The valid combinations are:

```python
if stimulus == timeseries and response == timeseries:
   pass
elif response == VoltageClampSeries:
   if stimulus != VoltageClampStimulusSeries:
     raise(...)
elif response == CurrentClampSeries:
   if stimulus != CurrentClampStimulusSeries:
     raise(...)
elif response == IZeroClampSeries:
  if stimulus is not None:
    raise(...)
else:
   raise(...)
```

**Comment by bendichter** [comment]
I like these checks, though this would create errors on read for pynwb files that are technically to spec but have one of these mistakes. If a file is written in MatNWB where these checks don't exist, then it may not be able to be read in pynwb. So maybe it's better if we throw warnings instead?

**Comment by t-b** [comment]
These checks are applied during write in pynwb only. So this should not be a problem for existing buggy data.
