### ISSUE TITLE
Avoid using `ic` as abbreviation for icephys

### ISSUE THREAD

**Issue by t-b** [oruebel/ndx-icephys-meta#36]
Please don't use the `ic` abbreviation for icephys as in icephys `ic` means CurrentClamp. I think `icephys` is better.

@timjarsky

**Comment by oruebel** [comment]
We should also have add_icephys_electrode and show a warning for add_ic_electrode in pynwb. In addition the tutorials should use the the function call.

See https://github.com/NeurodataWithoutBorders/pynwb/issues/1181
