### ISSUE TITLE
Example notebooks should use either current clamp or voltage clamp

### ISSUE THREAD

**Issue by rly** [oruebel/ndx-icephys-meta#38]
The example notebooks add a `CurrentClampStimulusSeries` and a `VoltageClampSeries` as stimulus and response to the `NWBFile`. These types are semantically incompatible. The `CurrentClampStimulusSeries` should be paired with a `CurrentClampSeries` and a `VoltageClampStimulusSeries` should be paired with a `VoltageClampSeries`.

I don't know if there are any exceptions to this rule (besides when a response is recorded without a stimulus and perhaps vice versa). If there are no exceptions, then perhaps the API should raise an error (or at least a warning) if incompatible types are passed into the new sweep table. At the very least, the example notebooks should use the typical use case. 

@t-b and @lvsltz please let me know if I am wrong here.

**Comment by oruebel** [comment]
Closing in favor of #22
