### ISSUE TITLE
adding response with no corresponding stimulus

### ISSUE THREAD

**Issue by bendichter** [oruebel/ndx-icephys-meta#41]
If there is a response, but no stimulus, like in the case of `IZeroClamp`, how are you supposed to add an entry to the intracellular recordings table? Are rows allows to be added that are missing a stimulus? I tried this and was not able to get it to work. All of the tests that add rows to that table provide both stimulus and response. If this is an intended use-case it should be tested.

**Comment by oruebel** [comment]
Yes, that is allowed. You should be able to simply omit the stimulus (or response) argument (or explicitly set it to None. Internally, what is happening is that the if you only provide a response (but no stimulus) then the stimulus is set to the same as the response with -1 as start/count index. The code that deals with this is:

https://github.com/oruebel/ndx-icephys-meta/blob/9522a1013541c61c020162dfc597215daf725bc3/src/pynwb/ndx_icephys_meta/icephys.py#L241-L303

**Comment by oruebel** [comment]
The following unit tests are testing this behavior, i.e., 1) add response without a stimulus and 2) add a stimulus without a response. Both tests are passing. 

https://github.com/oruebel/ndx-icephys-meta/blob/57f53bd0c55031cf5e53f0eb0160604689db2bb2/src/pynwb/ndx_icephys_meta/test/test_icephys.py#L335-L381
