### ISSUE TITLE
Remove nested type definition specifications

### ISSUE THREAD

**Issue by rly** [oruebel/ndx-icephys-meta#59]
The type definition of `IntracellularRecordingsTable` includes the type definitions for `IntracellularElectrodesTable`, `IntracellularStimuliTable`, and `IntracellularResponsesTable`. I understand that these three types are meant to be used only within the `IntracellularRecordingsTable`, but these types can still technically be used elsewhere, and if these types are defined outside of `IntracellularRecordingsTable`, it would be easier to parse the schema and avoid edge cases that arise from having nested type definitions. 

I suggest moving the specifications for these types to the root level of the extension and using `neurodata_type_inc` to include them in the `IntracellularElectrodesTable` type.

**Comment by oruebel** [comment]
Thanks for the issue. I'll have a look. If I remember correctly this also requires me to write a custom object mapper because this changes the mapping behavior.
