### ISSUE TITLE
to_hierarchical_dataframe not working as intended

### ISSUE THREAD

**Issue by bendichter** [oruebel/ndx-icephys-meta#72]
In [here](https://github.com/catalystneuro/ndx-hierarchical-behavioral-data#usage), `syllable_start_time` is part of the syllable table, and should have the same level as `syllable_start_time`, but instead has the same level as the phonemes table. This is a general problem that occurs for the last column of the second-to-last columns in a table hierarchy.

![image (11)](https://user-images.githubusercontent.com/844306/86624715-ce44cd00-bf91-11ea-85b0-80409441cbd7.png)

**Comment by oruebel** [comment]
Fixed in https://github.com/NeurodataWithoutBorders/pynwb/pull/1383
