### ISSUE TITLE
to_denonormalized_table not working as intended

### ISSUE THREAD

**Issue by bendichter** [oruebel/ndx-icephys-meta#73]
Using the README [here](https://github.com/catalystneuro/ndx-hierarchical-behavioral-data#usage), using the latest dev branch. The column names in the last table are mangled:

![image (12)](https://user-images.githubusercontent.com/844306/86624947-3bf0f900-bf92-11ea-8303-d71e9efa51af.png)

**Comment by oruebel** [comment]
Fixed in https://github.com/NeurodataWithoutBorders/pynwb/pull/1383
