### ISSUE TITLE
Feature request: a key to map the nwbfile_in.stimulus to intracellular_recordings[n]["stimuli"]

### ISSUE THREAD

**Issue by anilbey** [oruebel/ndx-icephys-meta#74]
Hi, thanks for the great work first of all!

I think it would be easier for the end users to have a key to map the `nwbfile_in.stimulus` to `intracellular_recordings[n]["stimuli"]` in the `intracellular_recordings[n]["stimuli"]` table.
A column with the name of the stimulus dataset in the intracellular_recordings table would be nice to have.

What do you think?

**Comment by oruebel** [comment]
If I understand your suggestion correctly, what we have is a column with link a to the stimuli in ``nwbfile_in.stimulus``, and in addition you would like to have a column with just the name of the dataset, i.e., effectively:

```names = [ d.name for d in intracellular_recordings[n]["stimuli"]]```

From a schema perspective, we should not duplicate information in columns, to avoid issues where the column with the names of the stimuli is inconsistent with the actual stimuli that are being linked to. Instead, I would suggest adding a convenience function in the API that would provide that information. If we want to get fancy, we could even make it look like a read-only column in the table.

**Comment by anilbey** [comment]
Actually just changing the id of this pandas series stored at `nwbfile_in.intracellular_recordings["stimuli"]["stimulus"]` from the integer index to the name of the dataset would be the best I think.

Right now `nwbfile_in.intracellular_recordings["stimuli"]["stimulus"]` looks like this
id
0      (0, 150, ccss__pulser__0001 pynwb.icephys.Curr...
1      (0, 150, ccss__pulser__0006 pynwb.icephys.Curr...
2      (0, 150, ccss__pulser__0011 pynwb.icephys.Curr...
3      (0, 150, ccss__pulser__0016 pynwb.icephys.Curr...
4      (0, 150, ccss__pulser__0106 pynwb.icephys.Curr...
...

The id is an integer that cannot be used to refer to `nwbfile_in.stimulus`.

To find the corresponding metadata to the `nwbfile_in.stimulus`, one needs to search the pandas series of tuples above.
Instead it would be great to use a key (e.g. name of the dataset) to map the data to metadata in constant time without having to search all entries.

**Comment by oruebel** [comment]
Thanks for the suggestion. Sounds reasonable.

**Comment by oruebel** [comment]
I added documentation for how to augment the DataFrames with information from the stimulus/response here https://github.com/NeurodataWithoutBorders/pynwb/blob/34bb0edd3a211dca92f3c12ce7fb63f8c7885a40/docs/gallery/domain/plot_icephys_pandas.py#L291-L307 Replacing the ``id`` directly is problematic as some users rely on the ids, but rather we need to add this information separately. For now I have addressed this in the documentation.
