### ISSUE TITLE
Storing data from multiple electrodes?

### ISSUE THREAD

**Issue by rly** [oruebel/ndx-icephys-meta#75]
@rightbower asks, can these new hierarchical tables be used to store data from multiple electrodes in the same experiment? If not, what is the recommended strategy for storing such data?

**Comment by oruebel** [comment]
The short answer is yes. For the slightly longer answer let me break this into a few steps. First, lets ignore this extension for a second. The current NWB 2.x schema allows you to store icephys recordings from multiple electrodes, simply be creating separate InteracellularElectrode instances and corresponding PatchClampSeries recordings. What the extension adds is a way to describe the temporal, hierarchical organization of recordings into collections of simultaneous recordings, sequential recordings, repetitions, and experimental conditions. When recording from multiple electrodes simultaneously, you simply add each recording consisting of an IntracellularElectrode and a stimulus and response TimeSeries to the IntracellularRecordings table. The SimultaneousRecordingsTable then groups rows of the IntracellularRecordings together to describe which recordings were recorded simultaneously, and so on, until at the top level the ExperimentalConditionsTable groups all the repetitions together that were acquired under the same experimental conditions. The following tutorial describes this process in more detail https://www.youtube.com/watch?v=TClUoKA1pEU
