### ISSUE TITLE
sql-like "unique index" for the id column

### ISSUE THREAD

**Issue by lvsltz** [oruebel/ndx-icephys-meta#8]
`intracellular_recordings, ic_sweeps, ic_sweep_sequences, ic_runs` tables allow insertions of rows with the same `id`. 
I think `id` should be unique.

MWE:
```
nwbfile.add_ic_sweep(recordings=[0], id=12)
nwbfile.add_ic_sweep(recordings=[0], id=12)
nwbfile.ic_sweeps.to_dataframe()
```

**Comment by oruebel** [comment]
> I think `id` should be unique.

Agreed.

**Comment by oruebel** [comment]
@lvsltz #10 should fix this. This requires the latest version of HDMF as this depends on https://github.com/hdmf-dev/hdmf/pull/186
