### ISSUE TITLE
error on the README script when used with h5py>=3.1.0

### ISSUE THREAD

**Issue by anilbey** [oruebel/ndx-icephys-meta#81]
It raises this error when used with `h5py` 3.1.0 or 3.2.0.
`TypeError: No conversion path for dtype: dtype('<U9')` 

It may be due to the h5py 3.0.0 update.

**Comment by oruebel** [comment]
Thanks for the heads up. We are still working on updating HDMF/PyNWB to support h5py >3.0. I'll have a look to see if this is an issue with the extension itself or HDMF, but I assume it is most likely the problem that updating HDMF to the latest h5py is still in the works. The corresponding issues and PR's on HDMF are

https://github.com/hdmf-dev/hdmf/issues/458
https://github.com/hdmf-dev/hdmf/pull/480

**Comment by wvangeit** [comment]
hi @oruebel, is there any ETA on the h5py>3.0 support? We need this extension for some open source code, and it would be good if our users don't have problems installing this dependency. Thanks.

**Comment by oruebel** [comment]
We are currently working on integrating the extension with NWB core. I would expect this will probably take another 2 weeks. h5py 3.x support is related to HDMF issue https://github.com/hdmf-dev/hdmf/issues/458 and the corresponding PR https://github.com/hdmf-dev/hdmf/pull/480. Can you please re-post your question there. CC @ajtritt

**Comment by oruebel** [comment]
@wvangeit sorry of the delay on this issue.  h5py3 support has been in released in PyNWB and HDMF. Porting of the extension to NWB core is largely complete now. I anticipate that we will finish the release by the end of this month. The
relevant PRs on PyNWB are https://github.com/NeurodataWithoutBorders/pynwb/pull/1349 and the related PR https://github.com/NeurodataWithoutBorders/pynwb/pull/1383.
