### ISSUE TITLE
id in ic_sweeps not referencing the id in intracellular_recordings

### ISSUE THREAD

**Issue by lvsltz** [oruebel/ndx-icephys-meta#9]
Adding an intracellular recording with a given id and then a sweep with the same id works. But generating the `ic_sweeps` table raises a `IndexError: list index out of range` error.

Note though that, if a sweep with index 0 is added, generating the table works just fine.

MWE:
```
nwbfile.add_intracellular_recording(electrode=electrode,
                                    stimulus=stimulus,
                                    response=response,
                                    id=10)
nwbfile.add_ic_sweep(recordings=[10], id=12) # replace 10 with 0 to fix
nwbfile.ic_sweeps.to_dataframe()
```

**Comment by oruebel** [comment]
In ``nwbfile.add_ic_sweep(recordings=[10],...`` the ``recordings`` parameter expects a list of the indices of the rows, not a list of id's. I'll add an example how to do this with id's. Sorry for the confusion.

**Comment by oruebel** [comment]
I still need to update the example, but https://github.com/hdmf-dev/hdmf/pull/187 should address this

**Comment by oruebel** [comment]
@lvsltz  I've added an example for how to index by id in #11 I'm waiting for https://github.com/hdmf-dev/hdmf/pull/187 to be merged, but all you need to do to search for rows with a given id is:

```nwbfile.runs.id == [10, 20]```

This will return a list of ints with the indices of all rows in the runs table that have the ids 10 or 20.

**Comment by lvsltz** [comment]
> the `recordings` parameter expects a list of the indices of the rows, not a list of id's.

Not sure I fully understand the need for both row index and id. If id is enforced to be unique (#10), why can't it simply be used further upstream ?
